### ISSUE TITLE
Konfig nginx例子文档写的是啥啥啥啊？

### ISSUE THREAD

**Issue by east4ming** [kcl-lang/konfig#10]
## Bug Report

```
完成编译，可以看到 3 个资源：

一个 name 为 nginx-exampledev 的 Deployment
一个 name 为 nginx-example 的 Namespace
一个 name 为 nginx-example 的 Service
```

但是，你给的例子结果是这个啊:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleappprod
  namespace: sampleapp
```

我想请问一下：

1. `一个 name 为 nginx-exampledev 的 Deployment` 咋来的？
2. `一个 name 为 nginx-example 的 Namespace` 又是咋来的？

### 1. Minimal reproduce step (Required)

中文文档：<https://www.kcl-lang.io/zh-CN/docs/user_docs/guides/working-with-konfig/guide#1-%E9%85%8D%E7%BD%AE%E7%BC%96%E8%AF%91>

### 2. What did you expect to see? (Required)

正确的文档

### 3. What did you see instead (Required)

错误的，看不懂的文档

### 4. What is your KCL components version? (Required)

- kcl: 0.9
- konfig: 0.5
