### ISSUE TITLE
strategy 更新策略 怎么配置

### ISSUE THREAD

**Issue by cx2c** [kcl-lang/konfig#26]
## General Question

```yaml
...
spec:
  selector:
    matchLabels:
      app: release-rest-server
      mesh: prod
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  replicas: 2
  template:
    metadata:
...
```

strategy 这一段，rollingUpdate 和 type， 用konfig怎么配置
