### ISSUE TITLE
使用中的两个问题，一个是亲和性 一个是volumeSource 是persistentVolumeClaim的情况

### ISSUE THREAD

**Issue by cx2c** [kcl-lang/konfig#28]
有两个使用上的问题请教一下
1. 我的pod的亲和性是按照下面配置的，我用konfig应该怎么写。
```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - release-rest-server
            topologyKey: kubernetes.io/hostname
```
2. 对于 volume是`persistentVolumeClaim`的情况，volumeSource 选哪个
![image](https://github.com/user-attachments/assets/7eba657b-f15e-4568-82a1-e0b8682b01e5)
